### ISSUE TITLE
(Bug: hubble) 

### ISSUE THREAD

**Issue by infintropy** [juno-fx/report#364]
### Dupe Check

- [X] I have [searched Juno's bugs](https://github.com/juno-fx/report/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and there are no duplicates

### Serivce this pertains to.

hubble

### URL in Hubble.

https://test.orion.redmond.ai/home/

### Browser

Chrome Based

### Describe the bug

```
Cannot read properties of undefined (reading 'icon')
```
 It also is blocking the /home page from loading fully

### To reproduce

Visit home page. 

The only behavior that seems to have made this occur was when I went to check for an API created workstation

### Expected behavior

Home is usually working (we are currently down)

### Screenshots

<img width="527" alt="image" src="https://github.com/user-attachments/assets/f7a3ab82-6519-478e-8bca-103315a9873e" />

### Regression

Yes, this bug started recently or with an X Orion version

### Recent working Orion date

2024/01/09

### Does this block you from using Orion daily?

Yes, this issue prevents me from using Orion daily.

**Comment by infintropy** [comment]
Considering this a show-stopper (as practice), since I cannot circumvent as an admin user.  I will be rebuilding the orion app to see if it clears it near EOD. Let me know if you want me to keep it up for forensics. 

Great ticket automation btw

**Comment by aldmbmtl** [comment]
Can you flush your cookies and see if that frees it up?

**Comment by aldmbmtl** [comment]
I think this is related to this one: https://github.com/juno-fx/report/issues/358

**Comment by aldmbmtl** [comment]
@Anthonygen1 does this ring any bells?

**Comment by skeleturtle** [comment]
Thank you for putting in a bug ticket. We have an internal ticket created and are looking into the issue.

**Comment by infintropy** [comment]
1. I came back to the orion session after a bit, and it was working. Allowed me to move around the site.  I subsequently tried another workstation request from the openapi test screen, and ended up with the same issue now. 
2. `undefined is not an object (evaluating 'f.filter(t=>t.idx===e.idx)[0].icon')` This is the error that shows up when I try the page from a fresh (newly authenticated) browser.

For now im just going to stop trying to use the openapi button except for GETs :) and test the workstation request with requests

**Comment by aldmbmtl** [comment]
Were you able to request a new workstation using the UI instead of the API?

**Comment by infintropy** [comment]
I havent tried. This time when I did it via API (from a requests call inside an orion wkst), I did notice in webb
```
0)
INFO:     10.42.1.4:57454 - "GET /webb/thumb/meta/null HTTP/1.1" 404 Not Found
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "requests/models.py", line 974, in json
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 338, in decode
  File "json/decoder.py", line 356, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Seems to correlate.

The same behavior occurs when I do it via API outside of the OpenAPI panel as does with it.

**Comment by aldmbmtl** [comment]
Both of those errors are normal operation for that. 

The kuiper error is expected. It is just a warning.

The webb error is just it trying to pull a thumbnail which doesn't exist. That is also exist.

Do you have a screen recording of it failing when you make the internal API request from the workstation?

**Comment by aldmbmtl** [comment]
This has been addressed in the rc for Hubble.

Here: https://github.com/juno-fx/hubble/issues/372

**Comment by infintropy** [comment]
So we are running into this one again, but it didnt start until I added a second workstation definition in git. 
Behavior that may have triggered it: I mistakenly placed the same metadata name within each of the definitions.  After this was pushed, we saw the above. 

Can you remind us of mitigation steps between when Hubble refreshes?

**Comment by infintropy** [comment]
```
---
apiVersion: juno-innovations.com/v2
kind: Workstation
metadata:
  name: artist-gpu
spec:
  runtimeClassName: nvidia
  registry: docker.io/redmondai
  icon: "https://cdn-icons-png.flaticon.com/512/1985/1985582.png"
  label: "GPU Workstation Production"
  group: "Production"
  tag: "unstable-ubuntu-22-dcc1.1.25"
  repo: "polaris-workstation"
  cpu: "7"
  memory: "28Gi"
  gpu: true
  mode: "interactive"
  env:
    - name: "foundry_LICENSE"
      value: "4101@165.227.215.100"
    - name: "__GLX_VENDOR_LIBRARY_NAME"
      value: "nvidia"
    - name: "__NV_PRIME_RENDER_OFFLOAD"
      value: "1"
    - name: "JUNOGL_MODE"
      value: "true"
    - name: "NVIDIA_VISIBLE_DEVICES"
      value: "all"
    - name: NVIDIA_DRIVER_CAPABILITIES
      value: all
```
